### ISSUE TITLE
Allow installation without sudo

### ISSUE THREAD

**Issue by rahul0705** [bbugyi200/cookie#22]
This is a great tool but having to use sudo make it non-usable in controlled environments, if this could be run from a clone directory that would be phenomenal

**Comment by bbugyi200** [comment]
@rahul0705 What do you mean when you say "run from a clone directory"? As in `/home/user/.local/bin`, for example?

If that's the case, then I think one option would be to run `make PREFIX= DESTDIR=/home/user/.local install`. Would that mitigate this issue for you? If so, I can add that to the install documentation.

**Comment by rahul0705** [comment]
Yeah something like that works or maybe have it be able to run without an
installation? Something like git clone and add to path?

**Comment by bbugyi200** [comment]
@rahul0705 The problem with that approach is that `cookie` depends upon the `gutils.sh` script in [bashlibs](https://github.com/bbugyi200/bashlibs), so both of them would need to be added to the system's path (which is basically all `make install` does).

In 9ef663c00d176d38c512a3ba0299d40cae3bf3a5, I have fixed a few things in the Makefile that would have caused issues with my proposed approach (using the `DESTDIR` and `PREFIX` variables) and have added instructions for this approach to the README.

I am closing this issue since I think this approach suffices. Please let me know if there is a problem with this method of installation that I might have missed.
